# fly.toml app configuration file generated for job-searcher on 2025-10-11T22:14:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-searcher'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # Allow long-running requests (job processing can take 10+ minutes)
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20
  
  # Increase timeout for long-running job searches
  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
